apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-data
  namespace: hive
  labels:
    app.kubernetes.io/name: hive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
